### ISSUE TITLE
Deploy stand-alone RAG demo(s) on the test server

### ISSUE THREAD

**Issue by PGijsbers** [openml-labs/ai_search#2]
Deploy the docker container(s) on the test server, and configure port-forwarding so they can be accessed from anywhere.

**Comment by LiinXemmon** [comment]
![image](https://github.com/user-attachments/assets/9afcabc1-5836-4765-ac8d-8242ee529b22)

I have reconfigured the Docker containers, and now the entire pipeline can run using Docker. The files each container depends on and their communication are shown in the diagram above. Currently, the server needs to correctly proxy the 8501 port that Streamlit listens on, which has not yet been resolved.

**Comment by LiinXemmon** [comment]
The server works with adding following rules:
```
        RewriteEngine On
        RewriteCond %{REQUEST_URI} ^/ai-search$
        RewriteRule ^(.*)$ /ai-search/ [R=301,L]
        RewriteCond %{HTTP:Upgrade} =websocket
        RewriteRule /ai-search/(.*) ws://localhost:8501/$1 [P]
        RewriteCond %{HTTP:Upgrade} !=websocket
        RewriteRule /ai-search/(.*) http://localhost:8501/$1 [P]
```
In addition, `proxy`, `proxy_wstunnel`, `proxy_http` and `rewrite`module needs to be loaded.
