### ISSUE TITLE
Update the tutorials with new API

### ISSUE THREAD

**Issue by SubhadityaMukherjee** [openml-labs/ai_search#21]
I changed some things recently and have to reflect those in the developer tutorials.

**Comment by PGijsbers** [comment]
When creating an issue, please use a sentence or two to describe what it is about, so others can gauge whether or not they can help and/or take on the issue. Thanks!

**Comment by SubhadityaMukherjee** [comment]
Oh, good point. I was intending for this to be for me but I should have mentioned that. Thanks :)
