### ISSUE TITLE
Labeling Consistency Analysis

### ISSUE THREAD

**Issue by PGijsbers** [openml-labs/ai_search#23]
Everyone labeled some (dataset, query) pairs. But how consistent is this labeling? A few datasets were labelled twice, and one these we can do some analysis. This is important to gain insight to, so that we know how 'ground truth' are labels are.

**Comment by PGijsbers** [comment]
@LiinXemmon can you still share your findings here? it's going to be easier to find later on (especially since Slack hides messages after 3 months).

**Comment by LiinXemmon** [comment]
We selected a small subset of dataset IDs for redundant annotation, and then divided the annotations of the same dataset by different individuals into two groups. We conducted a consistency check on these two groups. The result shows Cohen's Kappa is 0.5884, which indicates moderate agreement. The disagreements are mainly differences in opinion. For example, for the dog image dataset, one labels (dog image, imaging, animal classification); the other labels only (dog image, imaging). No significant errors were found.
